db:
    restart: always
    image: mysql:5.6
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: changeme
        MYSQL_USER: art17
        MYSQL_PASSWORD: art17
        MYSQL_DATABASE: art17
web:
    # todo: switch to image
    build: ./art17-consultation 
    volumes:
        - ./art17-consultation/:/art17
    ports:
        - "5000:5000"
    links:
        - db
    env_file:
        - ./dev.env
